Discontinued the original code. Try the other new Versions and its still incomplete. So, use this as a changelog

Changelog:
idontrememberdaybutitsinmarch ; added the original beta(now discontinued)
may 10 2025 : added 2 new versions
