#if you didn't read the README, read it and this is uncomplete

import tkinter as tk
def get_country_info():
    country_name = entry.get()
    if country_name.lower() == "afghanistan":
        info_text.set('''Country Name : Afghanistan
              Area Mass : 652864 sq km, 252072 sq mi
              Population : 43,844,111
              Capital : Kabul
              Currency : Afghan Afghani
              Languages : Pushto, Dari
              National Animal : Snow Leopard
              National Bird : Golden Eagle
              National Flower : Tulip
              National Fruit : Pomegranate
              National Sport : Buzkashi''')
    elif country_name.lower() == "albania":
        info_text.set('''Country Name : Albania
             Area Mass : 28748 sq km, 11100 sq mi
             Population : 2,771,508
             Capital : Tiranë
             Currency : Albanian Lek
             Language : Albanian
             National Animal : Eagle
             National Bird : Eagle
             National Flower : Red Poppy
             National Fruit : Cherry
             National Sport : Football''')
    elif country_name.lower() == "algeria":
        info_text.set('''Country Name : Algeria
             Area Mass : 2381741 sq km, 919595 sq mi
             Population : 47,435,312
             Capital : Algiers
             Currency : Algerian dinar
             Languages : Arabic, Tamazight
             National Animal : Fennec Fox
             National Bird : Barbary Partridge
             National Flower : Iris
             National Fruit : Berber Maraschino Cherry
             National Sport : Football''')
    elif country_name.lower() == "andorra":
        info_text.set('''Country Name : Andorra
             Area Mass : 468 sq km, 181 sq mi
             Population : 82,904
             Capital : Andorra la Vella
             Currency : Euro
             Languages : Catalan
             National Animal : Bruna d'Andorra Cow
             National Bird : Lammergeier
             National Flower : Poet's Narcissus
             National Fruit : Mango
             National Sport : Football''')
    elif country_name.lower() == "angola":
        info_text.set('''Country Name : Angola
             Area Mass : 1246700 sq km, 481,400 sq mi
             Population : 38,736,266
             Capital : Luanda
             Currency : Angolan Kwanza
             Languages : Portuguese
             National Animal : Giant Sable Antelope
             National Bird : Red-Crested Turaco
             National Flower : Welwitschia
             National Fruit : Palm
             National Sport : Football''')
    elif country_name.lower() == "Antigua and Barbuda":
        info_text.set('''Country Name : Antigua and Barbuda
             Area Mass : 440 sq km, 170 sq mi
             Population : 94,096
             Capital : Saint John's
             Currency : East Caribbean Dollar
             Languages : English
             National Animal : European Fallow Deer
             National Bird : Magnificent Frigatebird
             National Flower : Agave Karatto
             National Fruit : Antigua Black Pineapple
             National Sport : Cricket''')
    elif country_name.lower() == "argentina":
        info_text.set('''Country Name : Argentina
             Area Mass : 2,780,085 km, 1,073,397 sq mi
             Population : 45,851,378
             Capital : Buenos Aires
             Currency : Argentine peso
             Languages : Spanish
             National Animal : Rufous Hornero
             National Bird : Rufous Hornero
             National Flower : Ceibo
             National Fruit : Apple'
             National Sport : Juego del pato''')
    else:
        info_text.set("Country information not available")


root = tk.Tk()
root.title("Country Information App")
label = tk.Label(root, text="Enter the name of the country: ")
label.pack()
entry = tk.Entry(root)
entry.pack()
button = tk.Button(root, text="Get Info", command=get_country_info)
button.pack()
info_text = tk.StringVar()
info_label = tk.Label(root, textvariable=info_text, wraplength=400, justify=tk.LEFT)
info_label.pack()
root.mainloop()
